---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/weslien/digitalocean_exporter

steps:
- name: build
  pull: always
  image: golang:alpine
  commands:
  - apk add -U git make
  - make build
  - make test
  - make vet
  - make lint

- name: release
  image: golang:alpine
  commands:
  - apk add -U git make
  - make release
  when:
    event:
    - tag

- name: docker
  image: plugins/docker
  settings:
    repo: weslien/digitalocean_exporter
    tag: [ '0.6.1', '0.6' ]
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  when:
    event:
    - tag

- name: github
  image: plugins/github-release
  settings:
    files: dist/*
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  when:
    event:
    - tag

